/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.biblioteca;

import com.mycompany.biblioteca.model.ModelLivros;
import static com.mycompany.biblioteca.registrarlivro.Livros;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno TDS
 */
public class livrosloja extends javax.swing.JDialog {
    public static ArrayList<ModelLivros> LivrosAlugados = new ArrayList<>();
    DefaultTableModel modelList = new DefaultTableModel();
    /**
     * Creates new form livrosloja
     */
    public livrosloja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        botao = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        alugar = new javax.swing.JButton();
        indice = new javax.swing.JTextField();
        devolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        botao.setText("Listar");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        alugar.setText("Alugar");
        alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alugarActionPerformed(evt);
            }
        });

        indice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceActionPerformed(evt);
            }
        });

        devolver.setText("Devolver");
        devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao)
                        .addGap(42, 42, 42)
                        .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(comprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alugar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(devolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao)
                    .addComponent(comprar)
                    .addComponent(alugar)
                    .addComponent(indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devolver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private boolean botaoClicado = false;
    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
       if (botaoClicado) {
        return;
    }
        
        modelList.addColumn("Numeração");
        modelList.addColumn("Titulo");
        modelList.addColumn("Autor");
        modelList.addColumn("Categoria");
        modelList.addColumn("Ano");
        
        for(ModelLivros Listar : Livros) {
            modelList.addRow(new Object[] {
                Listar.getIndice(),Listar.getAutor(),Listar.getTitulo(),Listar.getCategoria(),Listar.getAno()
            });
        }
        tabela.setModel(modelList);
        tabela.setDefaultEditor(Object.class, null);
            botaoClicado = true;
            botao.setEnabled(false);
    }//GEN-LAST:event_botaoActionPerformed
    
    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
    String indiceText = indice.getText();
        if (indiceText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um índice válido");
            return;
        }        
    String indiceD = indice.getText();

    for (ModelLivros livro : Livros) {
        if (livro.getIndice().equals(indiceD)) {
            Livros.remove(livro);
            JOptionPane.showMessageDialog(this, "Livro comprado");
            this.dispose();
            break;
        } else {
            JOptionPane.showMessageDialog(this, "Livro não encontrado");
            }
        }
    }//GEN-LAST:event_comprarActionPerformed

    private void indiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceActionPerformed

    }//GEN-LAST:event_indiceActionPerformed

    private void alugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alugarActionPerformed
            String indiceText = indice.getText();
        if (indiceText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um índice válido");
            return;
        }        
    String indiceD = indice.getText();
    
    for (ModelLivros livro : Livros) {
        if (livro.getIndice().equals(indiceD)) {
            LivrosAlugados.add(livro);
            Livros.remove(livro);
            JOptionPane.showMessageDialog(this, "Livro alugar");
            this.dispose();
            break;
        } else {
            JOptionPane.showMessageDialog(this, "Livro não encontrado");
        }
    }
    }//GEN-LAST:event_alugarActionPerformed

    private void devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverActionPerformed
              String indiceText = indice.getText();
        if (indiceText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um índice válido");
            return;
        }        
    String indiceD = indice.getText();
    
    for (ModelLivros livro : LivrosAlugados) {
        if (livro.getIndice().equals(indiceD)) {
            LivrosAlugados.remove(livro);
            Livros.add(livro);
            JOptionPane.showMessageDialog(this, "Livro devolvido");
            this.dispose();
            break;
        } else {
            JOptionPane.showMessageDialog(this, "Livro não encontrado");
        }
    }
    }//GEN-LAST:event_devolverActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(livrosloja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(livrosloja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(livrosloja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(livrosloja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                livrosloja dialog = new livrosloja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alugar;
    private javax.swing.JButton botao;
    private javax.swing.JButton comprar;
    private javax.swing.JButton devolver;
    private javax.swing.JTextField indice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
