/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.biblioteca;

import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;

/**
 *
 * @author Aluno TDS
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        loja = new javax.swing.JMenu();
        livros = new javax.swing.JMenuItem();
        registrar = new javax.swing.JMenu();
        registrarautor = new javax.swing.JMenuItem();
        registrarlivro = new javax.swing.JMenuItem();
        registrarcliente = new javax.swing.JMenuItem();
        historico = new javax.swing.JMenu();
        listaautores = new javax.swing.JMenuItem();
        listaclientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 90)); // NOI18N
        jLabel4.setText("Biblioteca");

        loja.setText("Loja");

        livros.setText("Livros");
        livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosActionPerformed(evt);
            }
        });
        loja.add(livros);

        jMenuBar1.add(loja);

        registrar.setText("Registrar");

        registrarautor.setText("Registrar Autor");
        registrarautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarautorActionPerformed(evt);
            }
        });
        registrar.add(registrarautor);

        registrarlivro.setText("Registrar Livro");
        registrarlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarlivroActionPerformed(evt);
            }
        });
        registrar.add(registrarlivro);

        registrarcliente.setText("Registrar Cliente");
        registrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarclienteActionPerformed(evt);
            }
        });
        registrar.add(registrarcliente);

        jMenuBar1.add(registrar);

        historico.setText("Histórico");

        listaautores.setText("Lista de Autores");
        listaautores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaautoresActionPerformed(evt);
            }
        });
        historico.add(listaautores);

        listaclientes.setText("Lista de Clientes");
        listaclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaclientesActionPerformed(evt);
            }
        });
        historico.add(listaclientes);

        jMenuBar1.add(historico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarlivroActionPerformed
        registrarlivro registrarolivro = new registrarlivro(this,true);
        registrarolivro.setVisible(true);
    }//GEN-LAST:event_registrarlivroActionPerformed

    private void registrarautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarautorActionPerformed
        registrarautor registraroautor = new registrarautor(this,true);
        registraroautor.setVisible(true);
    }//GEN-LAST:event_registrarautorActionPerformed

    private void registrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarclienteActionPerformed
        registrarcliente registrarolivro = new registrarcliente(this,true);
        registrarolivro.setVisible(true);
    }//GEN-LAST:event_registrarclienteActionPerformed

    private void livrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosActionPerformed
        livrosloja mostrarlivros = new livrosloja(this, true);
        mostrarlivros.setVisible(true);
    }//GEN-LAST:event_livrosActionPerformed

    private void listaautoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaautoresActionPerformed
        listadeautores historicodcompra = new listadeautores(this, true);
        historicodcompra.setVisible(true);
    }//GEN-LAST:event_listaautoresActionPerformed

    private void listaclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaclientesActionPerformed
        listadeclientes historicodemprestimo = new listadeclientes(this, true);
        historicodemprestimo.setVisible(true);
    }//GEN-LAST:event_listaclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkPurpleIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu historico;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaautores;
    private javax.swing.JMenuItem listaclientes;
    private javax.swing.JMenuItem livros;
    private javax.swing.JMenu loja;
    private javax.swing.JMenu registrar;
    private javax.swing.JMenuItem registrarautor;
    private javax.swing.JMenuItem registrarcliente;
    private javax.swing.JMenuItem registrarlivro;
    // End of variables declaration//GEN-END:variables
}
